# Generated by Django 5.2.12 on 2026-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("menu", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
