# Generated by Django 4.2.29 on 2026-06-03 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lunch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_rating', to='reservations.lunch')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
